export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILED = "UPLOAD_FAILED";

export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_FAILED = "DATA_FAILED";

export const COMPARATOR_REQUEST = "COMPARATOR_REQUEST";
export const COMPARATOR_SUCCESS = "COMPARATOR_SUCCESS";
export const COMPARATOR_FAILED = "COMPARATOR_FAILED";

export const IMAGE_ADD_SUCCESS = "IMAGE_ADD_SUCCESS";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";

export const INGREDIENT_ADD_SUCCESS = "INGREDIENT_ADD_SUCCESS";
export const INGREDIENT_DELETE_SUCCESS = "INGREDIENT_DELETE_SUCCESS";

export const RESULT_REQUEST = "RESULT_REQUEST";
export const RESULT_SUCCESS = "RESULT_SUCCESS";
export const RESULT_FAILED = "RESULT_FAILED";

export const URL_ADD_SUCCESS = "URL_ADD_SUCCESS";
